import os
isnbuckets = {
    "add":[],
    "adc":[],
    "adiw":[],
    "sub":[],
    "subi":[],
    "sbc":[],
    "sbci":[],
    "sbiw":[],
    "and":[],
    "andi":[],
    "or":[],
    "ori":[],
    "eor":[],
    "com":[],
    "neg":[],
    "sbr":[],
    "cbr":[],
    "inc":[],
    "dec":[],
    "tst":[],
    "clr":[],
    "ser":[],
    "mul":[],
    "muls":[],
    "mulsu":[],
    "fmul":[],
    "fmuls":[],
    "fmulsu":[],
    "des":[],
    "rjmp":[],
    "ijmp":[],
    "eijmp":[],
    "jmp":[],
    "rcall":[],
    "icall":[],
    "eicall":[],
    "call":[],
    "ret":[],
    "reti":[],
    "cpse":[],
    "cp":[],
    "cpc":[],
    "cpi":[],
    "sbrc":[],
    "sbrs":[],
    "sbic":[],
    "sbis":[],
    "brbs":[],
    "brbc":[],
    "breq":[],
    "brne":[],
    "brcs":[],
    "brcc":[],
    "brsh":[],
    "brlo":[],
    "brmi":[],
    "brpl":[],
    "brge":[],
    "brlt":[],
    "brhs":[],
    "brhc":[],
    "brts":[],
    "brtc":[],
    "brvs":[],
    "brvc":[],
    "brie":[],
    "brid":[],
    "mov":[],
    "movw":[],
    "ldi":[],
    "lds":[],
    "ld_X":[],
    "ld_X+":[],
    "ld_-X":[],
    "ld_Y":[],
    "ld_Y+":[],
    "ld_-Y":[],
    "ldd_Y+q":[],
    "ld_Z":[],
    "ld_Z+":[],
    "ld_-Z":[],
    "ldd_Z+q":[],
    "sts":[],
    "st_X":[],
    "st_X+":[],
    "st_-X":[],
    "st_Y":[],
    "st_Y+":[],
    "st_-Y":[],
    "std_Y+q":[],
    "st_Z":[],
    "st_Z+":[],
    "st_-Z":[],
    "std_Z+q":[],
    "lpm":[],
    "lpm_Z":[],
    "lpm_Z+":[],
    "elpm":[],
    "elpm_Z":[],
    "elpm_Z+":[],
    "spm":[],
    "spm_Z+":[],
    "in":[],
    "out":[],
    "push":[],
    "pop":[],
    "xch_Z":[],
    "las_Z":[],
    "lac_Z":[],
    "lat_Z":[],
    "lsl":[],
    "lsr":[],
    "rol":[],
    "ror":[],
    "asr":[],
    "swap":[],
    "sbi":[],
    "cbi":[],
    "bst":[],
    "bld":[],
    "bset":[],
    "bclr":[],
    "sec":[],
    "clc":[],
    "sen":[],
    "cln":[],
    "sez":[],
    "clz":[],
    "sei":[],
    "cli":[],
    "ses":[],
    "cls":[],
    "sev":[],
    "clv":[],
    "set":[],
    "clt":[],
    "seh":[],
    "clh":[],
    "break":[],
    "nop":[],
    "sleep":[],
    "wdr":[]
}
filelist=os.listdir()
for x in filelist:
    if x.endswith(".lst"):
      os.system('python tameListing.py '+x)
for x in os.listdir("stats"):
    if x.endswith(".cnt"):
      f=open("stats/"+x)
      lines=f.readlines()
      for l in lines:
        splitline=l.split(',')
        isnbuckets[splitline[0]].append(splitline[1][:-1])
countfile = "stats/totals.csv"
f5=open(countfile,"w")
for x in isnbuckets:
    print(isnbuckets[x])
    line=x
    for y in isnbuckets[x]:
        line = line+","+str(y)
    print(line,file = f5)
mdfile = "stats/totals.md"
f6=open(mdfile,"w")
print("| Instruct | count |",file = f6)
for x in isnbuckets:
    line=x
    for y in isnbuckets[x]:
        line = "| "+line.rjust(8)+" | "+str(y).rjust(5);
print(line,file = f6)
